export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const VERIFY_TOKEN = "VERIFY_TOKEN";
export const VERIFY_TOKEN_ERROR = "VERIFY_TOKEN_ERROR";

export const LOGOUT = "LOGOUT";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_ALL_PRODUCTS_ERROR = "FETCH_ALL_PRODUCTS_ERROR";

export const FETCH_PRODUCT_DETAILS_BY_ID = "FETCH_PRODUCT_DETAILS_BY_ID";
export const FETCH_PRODUCT_DETAILS_BY_ID_ERROR =
  "FETCH_PRODUCT_DETAILS_BY_ID_ERROR";

export const FETCH_PRODUCTS_BY_DISTRIBUTOR_ID =
  "FETCH_PRODUCTS_BY_DISTRIBUTOR_ID";
export const FETCH_PRODUCTS_BY_DISTRIBUTOR_ID_ERROR =
  "FETCH_PRODUCTS_BY_DISTRIBUTOR_ID_ERROR";

export const FETCH_ALL_DISTRIBUTORS = "FETCH_ALL_DISTRIBUTORS";
export const FETCH_ALL_DISTRIBUTORS_ERROR = "FETCH_ALL_DISTRIBUTORS_ERROR";
